/** Next/React **/
import Head from "next/head";

/** NPM **/

/** Project Imports **/
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: "Adamsgården",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <html lang="dk">
        <body>
          <Header></Header>
          {children}
          <Footer></Footer>
        </body>
      </html>
    </>
  );
}
